### ISSUE TITLE
Multifold Possible?

### ISSUE THREAD

**Issue by SriMaddy** [worldline/FoldableLayout#2]
Can we set maximum number of times the card can be unfolded?

**Comment by vincentbrison** [comment]
Hi, sorry of the late response.
You can do that, but this is certainly not the role of the FoldableLayout which is a view to implement such behavior. Since you have callbacks to tracks events on the FoldableLayout, you can track in your controller the number of times the card have been unfolded and then disable fold / unfold call.
BR
